; Exercise 1.14-1.15

; Exercise 1.14. Draw the tree illustrating the process generated by the count-change procedure of section 1.2.2 in making change for 11 cents. What are the orders of growth of the space and number of steps used by this process as the amount to be changed increases?

; Solution:

; Illustration: https://photos.app.goo.gl/un7nhprkj7ihsbBw9
; The tree-recursive count-change procedure requires Θ(n) space and Θ(n²)

; ***********************************************************

; Exercise 1.15. The sine of an angle (specified in radians) can be computed by making use of the approximation sinx≈x if x is sufficiently small, and the trigonometric identity

; sin(x) = 3sin(x/3) - 4sin³(x/3)

; to reduce the size of the argument of sin. (For purposes of this exercise an angle is considered "sufficiently" small if its magnitude is not greater than 0.1 radians.) These ideas are incorporated in the following procedures:

(define (cube x) (* x x x))
(define (p x) (- (* 3 x) (* 4 (cube x))))
(define (sine angle)
  (if (not (> (abs angle) 0.1))
      angle
      (p (sine (/ angle 3.0)))))


; a. How many times is the procedure p applied when (sine 12.15) is evaluated?
; b. What is the order of growth in space and number of steps (as a function of a) used by the process generated by the sine procedure when (sine a) is evaluated?

; Solution a:
(sine 12.15)
(p (sine 4.05))
(p (p (sine 1.35)))
(p (p (p (sine 0.45)))
(p (p (p (p (sine 0.15))))
(p (p (p (p (p (sine 0.05)))))

; So the procedure p is applied 5 times.

; Solution b:
; The order of growth in space and steps is the ceiling of log₃(a/0.1), which is Θ(log a).
